name = "ReefGuideAPI"
uuid = "45c573e6-5605-41d1-a10b-0e5ac5982b4e"
authors = ["Takuya Iwanaga", "Benjamin Grier"]
version = "0.1.0"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiskArrays = "3c3547ce-8d99-4f5e-a174-61eb10b00ae3"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
FLoops = "cc61a311-1640-44b5-9fba-1b764f453329"
GeoDataFrames = "62cb38b5-d8d2-4862-a48e-6a340996859f"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoParquet = "e99870d8-ce00-4fdd-aeee-e09192881159"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"
